const CONTENT_FIELD_KEY = {
  ID: "content-id",
  NAME: "content-name",
  DESCRIPTION: "content-description",
  THEME: "content-theme",
  CUSTOMIZE_SCHEDULE_FOR_EACH_CHANNEL:
    "content-customize-schedule-for-each-channel",
  PUBLISH_DATE: "content-publish-date",
  PUBLISH_REGULARLY: "content-publish-regularly",
  SCHEDULE_CHANNEL: "content-schedule-channel",
  DATE_FROM: "content-date-from",
  DATE_UNTIL: "content-date-until",
  TIME: "content-time",
  PERSONA: "content-persona",
  PROJECT: "content-project",
  CAMPAIGN: "content-campaign",
  CHANNELS: "content-channels",
  STATUS: "content-status",
  START_DATE: "startDate",
  END_DATE: "endDate",
  APPROVAL: "content-approval",
  CONTENT_THEMES: "content-themes",
  CANVA_EXPORTED_URL: "canva-exported-url",
  CANVA_DESIGN_ID: "canva-design-id",
  DAM: "dam",
  EDIT: "content-edit",
};

const ESI_CONTENT_API_RESPONSE_FIELD_KEY = {
  ID: "id",
  HEADLINE: "headline",
  CHANNEL_DESCRIPTIONS: "channel_descriptions",
  THEME: "theme",
  CUSTOMIZE_SCHEDULE_FOR_EACH_CHANNEL: "customize_schedule_for_each_channel",
  PUBLISH_DATE: "publish_date",
  PUBLISH_REGULARLY: "publish_regularly",
  SCHEDULE_CHANNEL: "schedule_channel",
  DATE_FROM: "date_from",
  DATE_UNTIL: "date_until",
  TIME: "time",
  PERSONA: "personas",
  CAMPAIGN: "campaign",
  PROJECT: "project",
  STATUS: "status",
  CHANNEL_ATTACHMENTS: "channel_attachments",
  CONTENT_THEMES: "content_themes",
  CONTENT_TO_POST: "content_to_post",
  CANVA_EXPORTED_URL: "canva_exported_url",
  CANVA_DESIGN_ID: "canva_design_id",
  DAM: "dam",
  CHANNELS: "channels",
};

export { CONTENT_FIELD_KEY, ESI_CONTENT_API_RESPONSE_FIELD_KEY };
