const FORM_FIELD_TYPE = {
  INPUT: 1,
  TEXTAREA: 2,
  CHECKBOX: 3,
  NUMBER: 4,
  DROPDOWN: 5,
  IMAGE: 6,
  DATE: 7,
  DATERANGE: 8,
  SELECTION: 9,
  TAB: 10,
  CANVA: 11,
};

const FORMAT_DATE = "dd/MM/yyyy";

export { FORM_FIELD_TYPE, FORMAT_DATE };
