const FORM_FIELD_TYPE = {
  INPUT: 1,
  TEXTAREA: 2,
  CHECKBOX: 3,
  NUMBER: 4,
  DROPDOWN: 5,
  IMAGE: 6,
  DATE: 7,
  DATERANGE: 8,
  SELECTION: 9,
  TAB: 10,
  PASSWORD: 11,
  CANVA: 12,
  LABELCARD: 13,
  INFORMATION: 14,
  LABELBTN: 15,
  SELECTIONPERSONA: 16,
  DESCRIPTION: 17,
  DAM: 18
};

const FORMAT_DATE = 'dd/MM/yyyy';

export { FORM_FIELD_TYPE, FORMAT_DATE };
